[VENTUS][fix]divergent analyse problem
THU-DSP-LAB/llvm-project pull request #109
Opened 2024-04-16 06:58 UTC by ziliangzl

1.kernel function argument is not divergent
2.GPRF32 is not divergent
3.allocate VGPR for f32 node, cause vmv.vx has problem with f32 type
# **DO NOT FILE A PULL REQUEST**

This repository does not accept pull requests. Please follow http://llvm.org/docs/Contributing.html#how-to-submit-a-patch for contribution to LLVM.

# **DO NOT FILE A PULL REQUEST**

2024-04-16 08:12 UTC, zhoujingya commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +    //     if(BaseBase->getIndex() == getVastartStoreFrameIndex())
No need to remove this?here is for vardic function arguments

2024-04-16 08:13 UTC, zhoujingya commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +    // auto &MFI = FLI->MF->getFrameInfo();
No need to remove this?here is for vardic function arguments

2024-04-16 08:15 UTC, zhoujingya requested changes

2024-04-16 08:15 UTC, zhoujingya commented on llvm/lib/Target/RISCV/RISCVInstrInfo.cpp
> +  // if (RISCV::GPRF32RegClass.contains(SrcReg) &&
Just remove

2024-04-16 08:15 UTC, zhoujingya commented on llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp
> +  if (dyn_cast<PHINode>(V) &&
For phinodes, just return true, because you don't know the branch come from divergent branch or not

2024-04-16 08:16 UTC, zhoujingya commented
这里的FPR的判断，你判断不出来的，tablegen里面也需要定义，你去参考一下IsSGPR

2024-04-17 14:16 UTC, zhoujingya commented on llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp
> +  if (dyn_cast<PHINode>(V) &&
> Phinodes shouldn't be source of divergent, it is always false , divergent is depend on RegisterClass type of cross basic block value in RISCVISelLowering.cpp:13500 isSDNodeSourceOfDivergence ,this is in DAG level not IR.

phi节点的分析会比较麻烦，之前我和小汪针对这个问题分析了一段时间，我建议先把phi节点处理成Divergent, 后续等你熟练了之后，再针对这个优化，还有一个问题你一起修复了，就是浮点的load/store指令生成问题

2024-04-17 14:18 UTC, zhoujingya commented
commit title格式问题，需要更详细一点，summary信息也要加上

2024-04-18 10:00 UTC, zhoujingya commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +    return VT == MVT::i32 ? &RISCV::GPRRegClass : &RISCV::VGPRRegClass;
这里用GPRF32有啥问题

2024-04-18 10:04 UTC, ziliangzl commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +    return VT == MVT::i32 ? &RISCV::GPRRegClass : &RISCV::VGPRRegClass;
用GPRF32，执行test_basic constant测试就会以非divergent执行，我修改load/store指令后测试结果仍然错误

2024-04-18 10:16 UTC, zhoujingya commented on llvm/lib/Target/RISCV/VentusInstrInfoF.td
> +def FLW  : RVInstI<0b010, OPC_LOAD_FP, (outs GPRF32:$rd),
这个指令的操作码有点问题，zfinx不支持flw/fsw,所以原则上，sw与fsw是同一条指令，build的时候会有个warning,这个可以向清华反映一下

2024-04-19 02:06 UTC, ziliangzl commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +    return VT == MVT::i32 ? &RISCV::GPRRegClass : &RISCV::VGPRRegClass;
更改PhiNode divergent判定逻辑后，这一句代码永远不会生效，因为RC默认为VGPR，isDivergent永远为true，进不到这句if里，恢复PhiNode代码的修改和这里的代码修改即可复现constant测试的错误

2024-04-19 02:25 UTC, ziliangzl commented on llvm/lib/Target/RISCV/VentusInstrInfoF.td
> +def FLW  : RVInstI<0b010, OPC_LOAD_FP, (outs GPRF32:$rd),
是反映需要添加flw/fsw指令吗？

2024-04-19 02:33 UTC, zhoujingya commented on llvm/lib/Target/RISCV/VentusInstrInfoF.td
> +def FLW  : RVInstI<0b010, OPC_LOAD_FP, (outs GPRF32:$rd),
> 是反映需要添加flw/fsw指令吗？
差不多这个意思，需要反映lw.f与lw指令共用了一个编码空间。因为gpr与gprf32物理上是等价的，这样在tablegen里面定义指令得时候会有冲突，需要开辟一个新的指令空间

2024-04-22 06:23 UTC, zhoujingya approved these changes

2024-04-22 07:58 UTC, merged

2024-04-22 08:12 UTC, Jules-Kong commented
No commit description and the simplest testcase.