[VENTUS][fix]Fix FLW/FSW instruction coding conflict
THU-DSP-LAB/llvm-project pull request #112
Opened 2024-04-25 02:49 UTC by ziliangzl

Replace FLW/FSW instruction with PseudoFLW/PseudoFSW

2024-04-25 03:09 UTC, zhoujingya reviewed
Test file changed or added?

2024-04-25 03:12 UTC, zhoujingya commented on llvm/lib/Target/RISCV/VentusInstrInfoF.td
> +                (SW  GPR:$rs2, GPR:$rs1, simm12:$imm12)>;
这样还是不能在汇编代码中区分是浮点还是标量，能在LW指令定义里面加一个默认参数字符串定义，当是浮点load的时候，后面oprstr拼接一个"f",默认的标量load就是拼接一个“”

2024-04-25 06:54 UTC, zhoujingya requested changes
Title format

2024-04-26 03:02 UTC, ziliangzl commented on llvm/lib/Target/RISCV/VentusInstrInfoF.td
> +                (SW  GPR:$rs2, GPR:$rs1, simm12:$imm12)>;
仍然相当于定义相同编码的两个指令，会导致冲突

2024-04-26 05:27 UTC, zhoujingya approved these changes

2024-04-26 05:28 UTC, merged