[VENTUS][NFC]Add compile guide in README
THU-DSP-LAB/llvm-project pull request #114
Opened 2024-04-26 08:45 UTC by ziliangzl

Explained how to generate ELF file step-by-step.

2024-04-26 09:42 UTC, zhoujingya commented on README.md
> +4. Compile essential library:
workitem里面包含了get_global_id，这里面应该告知用户使用自己编译的工具链或者使用我们发布的工具链，里面这些库都包含

2024-04-28 02:05 UTC, ziliangzl commented on README.md
> +4. Compile essential library:
我找到了`get_global_id`在`./install/lib/riscv32clc.o`中，但是在链接的时候会报错：
```
./install/bin/ld.lld -o vecadd.riscv -T utils/ldscripts/ventus/elf32lriscv.ld vecadd.o ./install/lib/crt0.o ./install/lib/riscv32clc.o -L./install/lib -lworkitem
ld.lld: error: ./install/lib/riscv32clc.o:(function erf(double vector[2]): .text._Z3erfDv2_d+0x24d0): relocation R_RISCV_BRANCH out of range: -6884 is not in [-4096, 4095]; references .LBB7_12
>>> referenced by subnormal_use_default.ll
>>> defined in ./install/lib/riscv32clc.o
```

2024-04-28 02:23 UTC, zhoujingya commented on README.md
> +4. Compile essential library:
@ziliangzl 看起来是一个relocation的错误

2024-04-28 02:32 UTC, zhoujingya requested changes

2024-04-28 02:32 UTC, zhoujingya commented on README.md
> +./install/bin/ld.lld -o vecadd.riscv -T utils/ldscripts/ventus/elf32lriscv.ld vecadd.o ./install/lib/crt0.o get_global_id.o -L./install/lib -lworkitem
加一个  “--gc-sections "参数看一看

2024-04-28 09:04 UTC, zhoujingya commented
@ziliangzl 能添加一个乘影自定义汇编代码的汇编文件一键编译成可知性文件的例子？

2024-04-28 09:07 UTC, zhoujingya commented on README.md
> +##### Compile step-by-step
4.1.1？

2024-04-29 07:59 UTC, zhoujingya commented on README.md
> +##### 4.1.3 compile assembly code to target file (`.s` to `.o`)
object?

2024-04-29 07:59 UTC, zhoujingya approved these changes
Fix comment and land it

2024-04-29 08:15 UTC, merged