[VENTUS][fix]Fix double add and mul operation
THU-DSP-LAB/llvm-project pull request #139
Opened 2024-07-24 02:49 UTC by ziliangzl

Passed test_geometrics in CTS.
Constant-Hoisting pass的作用是减少重复的常量加载，而立即数指令只能使用标量寄存器，这就导致在分支中寄存器状态会被修改，double浮点运算计算错误。

2024-07-24 14:32 UTC, zhoujingya commented
git pull --rebase main分支是一个更好的方法

2024-07-24 14:43 UTC, zhoujingya commented
https://github.com/THU-DSP-LAB/llvm-project/blob/main/llvm/include/llvm/CodeGen/TargetPassConfig.h#L196-L198

在RISCV后端禁用掉这个pass，尽量不要修改上层通用接口

2024-07-24 14:43 UTC, zhoujingya requested changes
参考`llvm/include/llvm/CodeGen/TargetPassConfig.h#L196`

2024-07-25 05:35 UTC, ziliangzl commented
Constant Hoisting pass没有`PassID`，没有办法使用`disablePass`，有其他接口能禁用pass吗?

2024-07-25 05:39 UTC, zhoujingya commented
> Constant Hoisting pass没有`PassID`，没有办法使用`disablePass`，有其他接口能禁用pass吗?
原则上可以为每一个pass创建ID

2024-07-25 05:46 UTC, ziliangzl commented
我知道在基类中有`getPassID( )`这个接口可以获得`PassID`，但是我不知道如何在`RISCVPassConfig`中获得pass实例，从而获得`PassID`

2024-08-02 14:15 UTC, zhoujingya commented
使用	`llvm/lib/Transforms/Scalar/ConstantHoisting.cpp`这个份文件里面的接口`TTI->getIntImmCostInst`来修改更为合适

2024-08-07 05:39 UTC, zhoujingfighting approved these changes

2024-08-07 05:40 UTC, zhoujingya approved these changes

2024-08-07 05:40 UTC, merged

2024-08-08 06:49 UTC, Jules-Kong commented
The operation of "Merge branch 'main' into double-operation" is not logical, please use "git pull --rebase origin main". 
When submitting code later, try to use one commit for each feature.