[VENTUS][fix] Fix insert vmv instruction bug when vmv instruction is in JOIN MBB
THU-DSP-LAB/llvm-project pull request #47
Opened 2023-10-25 06:50 UTC by zhoujingya

2024-01-02 04:54 UTC, dodohack commented on llvm/lib/Target/RISCV/VentusInsertJoinToVBranch.cpp
> +    unsigned NeedToBeInsertMBBNum = 0;
```
    // The number of MBBs where VMV instruction should be inserted into.
    unsigned NumMBB = 0;
```

2024-01-02 04:55 UTC, dodohack commented on llvm/lib/Target/RISCV/VentusInsertJoinToVBranch.cpp
>          MachineBasicBlock::iterator Insert = Pre->begin();
`Insert` -> `I`

2024-01-02 04:56 UTC, dodohack commented on llvm/lib/Target/RISCV/VentusInsertJoinToVBranch.cpp
>          MachineBasicBlock::iterator Insert = Pre->begin();
Iterator naming convention: `Insert` -> `I`.

2024-01-02 04:59 UTC, dodohack commented on llvm/lib/Target/RISCV/VentusInsertJoinToVBranch.cpp
> +        MBBMaybeInsertedInstr;
Can we have a better name for `MBBMaybeInsertedInstr`?

2024-01-02 05:50 UTC, dodohack requested changes
Coding style fix please.

2024-03-05 09:00 UTC, wangqinfan approved these changes
LGTM

2024-03-05 09:04 UTC, closed without merging